### ISSUE TITLE
Uncaught TypeError: polygon.getLatLngs is not a function

### ISSUE THREAD

**Issue by cliph** [itayo/IITC-Ingress-Maxfields-Exporter#10]
When clicking "IMF Export" in latest Chrome and latest IITC, receive the following error in the console:

Uncaught TypeError: polygon.getLatLngs is not a function

And no window is created or displayed. Happy to provide any other information.

**Comment by itayo** [comment]
Please provide info about drawtools

**Comment by cliph** [comment]
Running latest draw tools;

@version        0.7.0.20150917.154202

Have one polygon created

**Comment by itayo** [comment]
latest Chrome and latest IITC is that 
Is iitc =  0.25.2.20151111.74206 or 0.25.1.20150917.154202
What version of chrome. Windows or linux?

**Comment by itayo** [comment]
Please also export drawtool data for me :)

**Comment by cliph** [comment]
Chrome version: 46.0.2490.71 (64-bit), Mac OS X
IITC version: 0.25.1.20150917.154202
Draw tools version: 0.7.0.20150917.154202

Draw tool data:

[{"type":"marker","latLng":{"lat":43.64116965949445,"lng":-79.40960481762886},"color":"#a24ac3"},{"type":"marker","latLng":{"lat":43.645056,"lng":-79.411191},"color":"#a24ac3"},{"type":"polygon","latLngs":[{"lat":43.64986396690839,"lng":-79.41821336746216},{"lat":43.644763407370135,"lng":-79.41633582115173},{"lat":43.6457493940483,"lng":-79.41147565841673},{"lat":43.65071789954121,"lng":-79.41342830657959}],"color":"#a24ac3"}]

**Comment by itayo** [comment]
can yo also copy the intel link ?:)

**Comment by itayo** [comment]
it might have to
 do with those markers.

**Comment by cliph** [comment]
https://www.ingress.com/intel?ll=43.64342802953259,-79.40789222717284&z=16&pls=43.64986396690839,-79.41821336746216,43.644763407370135,-79.41633582115173_43.644763407370135,-79.41633582115173,43.6457493940483,-79.41147565841673_43.6457493940483,-79.41147565841673,43.65071789954121,-79.41342830657959_43.65071789954121,-79.41342830657959,43.64986396690839,-79.41821336746216

**Comment by cliph** [comment]
You're right, removed markers and now it works.

**Comment by itayo** [comment]
I will add a check of what type it is.)

Will fix when i get home:)
(out with daughter rite now)

**Comment by itayo** [comment]
This should now be fixed.

Br
Itayo

**Comment by itayo** [comment]
Than you pmodin for your quick support
