### ISSUE TITLE
Allow export from bookmarked portals

### ISSUE THREAD

**Issue by pmodin** [itayo/IITC-Ingress-Maxfields-Exporter#27]
To be able to create some multilayered BAFs 😸

**Comment by WheelOfTheLaw** [comment]
BIG plus one to this request!

**Comment by itayo** [comment]
What plugin is that?

**Comment by pmodin** [comment]
> What plugin is that?

"Bookmarks for maps and portals", `bookmarks-by-zaso`. If we developed functionality to export individual portals, or perhaps folders for export to Maxfields, it would be very easy to generate large field planning. 

Since portals doesn't show unless zoomed in, this seems like a natural workflow.

**Comment by itayo** [comment]
@pmodin  you know you are welcome to do a implementation  if you like :)

**Comment by itayo** [comment]
or suggest a implementation way.
I cant see the way forward for this

**Comment by pmodin** [comment]
Was thinking we could either plug into the Bookmark bar[1], or that we build a selector to the main IMF window where one can select the folder/portals for export, similar on how "Auto draw"[2] works. Solution [1] might be easier to use but I don't know if we should (ab)use that window, but otoh we're still dependant on the plugin to not introduce any breaking changes.

What do you think? I might have some time during next weekend to work on this, but it's pretty busy days at the moment.

The bookmark plugin holds all data we need for an export (name and latlng) so that's good 😄 

[1]
![image](https://cloud.githubusercontent.com/assets/1815201/15466610/c290de54-20da-11e6-92fa-e23ae4fd01d0.png)

[2]
![image](https://cloud.githubusercontent.com/assets/1815201/15466423/d419ce84-20d9-11e6-9f37-de938f848cff.png)

**Comment by itayo** [comment]
Im going to be computerless during june. 
But l try to find time to merge this if u are able to post it.

Until i go on vacation i wont have time to do any big things here unfortenly.


Also if u do things just BEFORE vacation u usually break stuff :+1:

**Comment by itayo** [comment]
@WheelOfTheLaw  this will be imlemented sooner or later.

If @pmodin  have time to submit an idea and codacy passes it i might just take it in.

Unfortenly i cant promise this to be implemented untill 0.2.0.0 release, and that is right now expected to be released in 2016-08-01

As this is the only issue right now for it.

If someone else makes a implementation that passes codacy and me, il take it in and release 0.2.0.0 earlier.

Br
Stefan
